name: Fetch guest tokens
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: update apt
        run: sudo apt-get update
      - name: Fetch data
        run: "echo hello"
